### PR TITLE
Feature/weather app

### PR DESCRIPTION
**Pull request by anapdh**
This branch features:

- Functions that hit the weather API taking a location and returning the weather data for that location.
- Functions that process the JSON data from the API and return an object with only the data you required for the app.
- Current location weather if permitted by the user;
- A simple form that lets users input their location and fetch the weather info.
- Weather display in Celsius or Fahrenheint;
- A ‘loading content’ component that displays from the time the form is submitted until the information comes back from the API.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job **Ana Paula** so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - App is functional and available online. 💯 

- ### To Improve
  
  - [x] [MANDATORY] Fix your MIT link from your README(it is returning page not found).
  - [x] [MANDATORY] The app should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: you can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
  - [x] [MANDATORY] It would be better to change the background according to received data. for example: if the weather is cloudy, then use the background with some clouds. if the weather is rainy, then use the background with some rains. etc. 

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work making the requested changes.
### Changes made 🌵 🌵 🌵 
- Background changes based on weather condition
- MIT license link fixed

### Changes to make 🙅🏿 🙅🏿 🙅🏿 
- Fix the toggle button. A user should be able to change the weather value between F and C.


### Martin Afani
#### Slack: whiz25

**Comment by anapdh** [comment]
Sorry, I forgot to deploy the button changes for °C and °F.
Updated.

**Review by oloomoses — APPROVED** [review]
## Congratulations, Project Aproved! :tada: :muscle: 
**Hello @anapdh,
Well done on making the changes suggested by the previous reviewers. You have passed all the requirements for this project :100:** 

**You can now merge and close this pr**

Happy Codding and best wishes in your next project :rocket: 

_slack: Oloo Moses_

**Pull request merged**
